### ISSUE TITLE
Graph making fails without NCM_labelfile

### ISSUE THREAD

**Issue by SPPearce** [IARCbioinfo/NGSCheckMate-nf#3]
Hi,

Firstly, thank you for implementing this, it is a useful interface to the NGSCheckMate package.
When I run this on a folder of bams, e.g. input_folder="bams", it fails at the graph making step because NCM_labelfile is undefined. 

Can you give an example of what the NCM_labelfile should look like, and maybe include code to exit gracefully if it is not given.

**Comment by nalcala** [comment]
Hi, 
Thanks for your interest in the pipeline! Indeed, I did some additions but did not update the readme. I will do it right now and also provide an option to deactivate the plots (which require a specific file that might not always be readily available). Stay tuned.

**Comment by nalcala** [comment]
Hi @SPPearce , 

commits https://github.com/IARCbioinfo/NGSCheckMate-nf/commit/3d13343fa25b7a4c88aec5c0f069322be5f73c01 and https://github.com/IARCbioinfo/NGSCheckMate-nf/commit/c376b437b696bb65799fe65e1c6974beb9fb07be should have solved the issue. Please tell me if something is not clear or not working on your side! Thanks again for trusting us with this pipeline :)

Best,

Nicolas

**Comment by SPPearce** [comment]
Hi Nicolas,

Thank you, that helps. 

Simon
